Bazaar/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'
urlpatterns = [
    # path('', views.inbox,name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation,name='new'),
]

Bazaar/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    # path('route', what to display in route, unique name)
    # what to display is filename.functionname
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    # this is default model from Django hence not defined in views.py
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    # loggedin same as index.html but with welcome user
    # user is login_redirected_url
    path('user/',views.loggedin,name='loggedin'),
    
    # default model from django
    path('logout/',LogoutView.as_view(),name='logout')
]

Bazaar/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    
]

Bazaar/item/urls.py
from django.urls import path

from . import views

app_name = 'item'
# frmo views.py the detail function is being called
urlpatterns = [
    path('<int:pk>/',views.detail, name='detail'),
    path('browse/',views.browse, name='browse'),
    path('add/', views.new,name='add'),
    #path('dashboard/', views.dashboard,name='dashboard')
    path('<int:pk>/edit/',views.edit,name='edit')
]

Bazaar/puddle/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include



urlpatterns = [
    path('',include('core.urls')),
    # 'route' after which all the next urls suffixes
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    # path('route',include(app_name.urls)
    path('inbox/', include('conversation.urls')),
    path('message/', include('message.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Bazaar/item/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name
    
# describing the fields in the table
# migrate each time you add a new class and register in admin.py
class Item(models.Model):
    # Category table is imported here so it checks which category it belongs to
    category= models.ForeignKey(Category, related_name='items',on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)
    price = models.FloatField()
    # in item_images the images are stores. Django will create that folder
    image=models.ImageField(upload_to='item_images', blank=True,null=True)
    is_sold=models.BooleanField(default=False)
    # Foreign Key is for many one relationship. User model is imported from django Auth
    # if you want to access all items of the User we can use the related_name param to access them
    created_by = models.ForeignKey(User, related_name='items',on_delete=models.CASCADE)
    # auto_now_add=True current date time
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name
    

Bazaar/item/forms.py
from django import forms
from .models import Item


INPUT_CLASSES = "w-full py-4 px-6 rounded-xl border"

class NewItemForm(forms.ModelForm):
    class Meta:
        # necessary to assign a model in py files that are in models.py to let Django know
        # by assigning this the class is referenced to Item class and its attributes
        model=Item
        # these fields become headings by default when you create a model
        # must be same as fields in model created
        fields = ('category','name', 'description','price', 'image')

        # forms.Select creates a drop down option
        # easier to set CSS for each widget in this case
        widgets = {
            'category': forms.Select(attrs={
            'class' : INPUT_CLASSES
        }),
            'name': forms.TextInput(attrs={
            'class' : INPUT_CLASSES
        }),
            'description': forms.Textarea(attrs={
            'class' : INPUT_CLASSES
        }),
            'price': forms.TextInput(attrs={
            'class' : INPUT_CLASSES
        }),
            'image': forms.FileInput(attrs={
            'class' : INPUT_CLASSES
        }),
        } 
    
class EditItemForm(forms.ModelForm):
    class Meta:
        # necessary to assign a model in py files that are in models.py to let Django know
        # by assigning this the class is referenced to Item class and its attributes
        model=Item
        # these fields become headings by default when you create a model
        fields = ('name', 'description','price', 'image', 'is_sold')

        # forms.Select creates a drop down option
        # easier to set CSS for each widget in this case
        widgets = {
            'name': forms.TextInput(attrs={
                # tailwind can be used
            'class' : INPUT_CLASSES
        }),
            'description': forms.Textarea(attrs={
            'class' : INPUT_CLASSES
        }),
            'price': forms.TextInput(attrs={
            'class' : INPUT_CLASSES
        }),
            'image': forms.FileInput(attrs={
            'class' : INPUT_CLASSES
        }),
        } 
    

Bazaar/item/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .forms import NewItemForm, EditItemForm
from .models import Category, Item

def browse(request):
    # getting the items for search bar
    # request is HTTP request
    # GET is HTTP 
    # .get('query') is http get url ?query=example
    # 'query' input tag value {{query}} '' is default
    # query is the name in the url http same as category
    query = request.GET.get('query', '' )
    # gets the category part of the url which is category.id
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items=Item.objects.filter(is_sold=False)

    if category_id:
        # category_id(1) is param of this items, category_id(2) is refrencing .GET one 
        items=items.filter(category_id=category_id)
    # if query is got then it will return True 
    if query:
        # if the name contains query(i) then query is processed
        # items is all the unsold Item
                            # where the name field contains the query string
        items=items.filter(Q(name__icontains = query) | Q(description__icontains= query))

    return render(request,'item/browse.html',{
                  'items':items,
                  'query' : query,
                  'categories' : categories,
                  'category_id': int(category_id)
    })



# this is when you click on a product
def detail(request, pk):
    item=get_object_or_404(Item,pk=pk)
    # category= item.category .category is a field in models, item is the object to which the field is called
    related_items = Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)
    return render(request, 'item/detail.html',{
        'related_items' : related_items,
        'item': item
    })

@login_required
def new(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            #commit False so that form isnt saved in database immediately
            # since we are redirecting back to detail we need to 
            # set item as the form so it is displayed in detail.html
            item=form.save(commit=False)

            # created_by is a field in models.py for Item
            item.created_by = request.user
            item.save()
            # after savind display details of the newly added item
            return redirect('item:detail',pk=item.id)
    else:
        form=NewItemForm()

    return render(request, 'item/form.html',{
        'form':form,
        'title': 'New item',
    })

@login_required
def edit(request, pk):
    # getting the item created by an user
    item = get_object_or_404(Item, pk=pk,created_by = request.user)
    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()
            # after savind display details of the newly added item
            return redirect('item:detail',pk=item.id)
    else:
        form=EditItemForm(instance=item)

    return render(request, 'item/form.html',{
        'form':form,
        'title': 'Edit item',
    })

# @login_required
# def dashboard(request):
#     return render(request,'item/dashboardmine.html')
        
    

Bazaar/item/templates/item/browse.html
{% extends 'core/base.html'%}

{%block title%} Items {%endblock%}

{%block content%}
<!--4 cols created-->
    <div class = "pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class = "col-span-1">
            <form method = "get" action = "{% url 'item:browse' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{query}}" placeholder = "Find a bike, a chair or a car">
                <button class='mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl'>Search</button>
            </form> 
            
            <hr class="my-6">
            <p class="font-semibold"> Categories</p>

            <ul>
                {% for category in categories%}
                <li class = "py-2 p-2 rounded-xl{% if category.id == category_id %} bg-gray-200 {%endif%}">
                    <!-- setting up the url format for when you click on a category-->
                    <!-- the {{query}} is used to reference -->
                    <!-- all categories are displayed-->
                    <a href = "{% url 'item:browse'%}?query={{query}}&category={{category.id}}">{{category.name}}</a>
                </li>
                {%endfor%}
            </ul>
            <hr class="my-6">
            <a href="{% url 'item:browse'%}" class="rounded-xl bg-teal-500 py-4 px-3 text-white">Clear</a>
        </div>
        <!--using 3 to display items-->
        <div class = "col-span-3">
            
            <div class="grid grid-cols-3 gap-3">
                {%for item in items%}
                <div>
                    <!--clicking on image redirects you to detail-->
                    <!--app_name.name='-'-->
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{item.image.url}}" class="rounded-t-xl">
                        </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-black-100">Price:{{item.price}}</p>
                    </div>
                    </a>
                </div>
                {% endfor %}
                 
            </div>
        </div>
    </div>    

{%endblock%}

Bazaar/item/templates/item/dashboardmine.html
{% extends 'core/base.html'%}

Bazaar/item/templates/item/detail.html
{% extends 'core/base.html'%}

{% block title%}{{item.name}} {%endblock%}

{%block content%}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{item.image.url}}" class="counded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb- text-3xl">{{item.name}}</h1><br>
        <p class="text-gray-500"><strong>Price: </strong>{{item.price}}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{item.created_by.username}}</p>
        
        {%if item.description%}
        <p class="text-gray-700"><strong>Description: </strong><br>{{item.description}}</p>
        {% endif %}

        {%if request.user == item.created_by%}
        <div class="mt-6 p-6 bg-white rounded-xl">
            <p class='text-lg text-black-500'> This is your item </p>
            <a href="{% url 'item:edit' item.id %}" class='rounded-xl text-lg bg-teal-500 inline-block mt-6 px-6 py-3 font-semibold text-white hover:bg-teal-700'>Edit</a>
            <!--item.id is the primary key and item is in  for item in items-->
        <a href="{% url 'dashboard:delete' item.id %}" class='rounded-xl text-lg bg-red-500 inline-block mt-6 px-6 py-3 font-semibold text-white hover:bg-red-700'>Delete</a>
        </div>
        {% else %}
            <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Contact Seller</a>
        {%endif%}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center"> Related Items</h2>

    <div class="grid grid-cols-3 gap-3">
        {%for item in related_items%}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{item.image.url}}" class="rounded-t-xl">
                </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{item.name}} </h2>
                <p class="text-black-100">Price:{{item.price}}</p>
            </div>
            </a>
        </div>
        {% endfor %}
         
    </div>
</div>
{%endblock%}

Bazaar/item/templates/item/form.html
{% extends 'core/base.html'%}

{% block title %} {{title}} {%endblock%}

<!--New Item-->
{% block content%}
<h1 class="mb-6 text-3xl">{{title}}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {%csrf_token%}

    <div class="space-y-4">
        <!--in form.as_p headings are taken as per field name-->
        {{form.as_p}}
    </div>
    {% if form.errors or form.non_field_errors%}
            <div class="bg-read-100 rounded-xl mb-3 p-6">
                {% for field in form%}
                {{ field.errors}}
                {% endfor%}

                {{ form.non_field_errors}}
                
            </div> 
            {% endif%}
     <button class="py-2 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"> Submit</button>
        </form>
 {%endblock%}