Bazaar/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    # path('route', what to display in route, unique name)
    # what to display is filename.functionname
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    # this is default model from Django hence not defined in views.py
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login'),
    # loggedin same as index.html but with welcome user
    # user is login_redirected_url
    path('user/',views.loggedin,name='loggedin'),
    
    # default model from django
    path('logout/',LogoutView.as_view(),name='logout')
]

Bazaar/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    
]

Bazaar/item/urls.py
from django.urls import path

from . import views

app_name = 'item'
# frmo views.py the detail function is being called
urlpatterns = [
    path('<int:pk>/',views.detail, name='detail'),
    path('browse/',views.browse, name='browse'),
    path('add/', views.new,name='add'),
    #path('dashboard/', views.dashboard,name='dashboard')
    path('<int:pk>/edit/',views.edit,name='edit')
]

Bazaar/message/urls.py
from django.urls import path
from . import views
app_name = 'message'

urlpatterns = [
    path('', views.inbox,name='inbox'),
    path('<int:pk>/',views.detail,name='detail')
]

Bazaar/puddle/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include



urlpatterns = [
    path('',include('core.urls')),
    # 'route' after which all the next urls suffixes
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    # path('route',include(app_name.urls)
    path('inbox/', include('conversation.urls')),
    path('message/', include('message.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Bazaar/core/models.py
from django.db import models

# Create your models here.

Bazaar/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# User is inbuilt in Django with username password and email
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    # no need of class Meta and model=User in login form because we are using default Django Auth form
    username= forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class':'w-full py-4 px-6 rounded-xl'
    }
    ))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class':'w-full py-4 px-6 rounded-xl'
    }
    ))


class SignupForm(UserCreationForm):
    # we are extending the signupform class with UserCreationForm
    # class Meta used for basic behaviour
    class Meta:
        # since we are using the default user from Django Auth system
        # also we have to create a model to let Django know from where it should take the fields
        model=User
        fields=('username','email','password1','password2')
    # in django UserCreationForm only certain conditions for username and pwd are available
    username= forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class':'w-full py-4 px-6 rounded-xl'
    }
    ))
    # widgets should be in class meta
    # if you change one input as the one given below you have to change all or they become seperate divs since 
    # represent different stylings and fields
    # widgets = {
    #     'email': forms.EmailInput(attrs={
    #         'class': 'w-full py-4 px-6 rounded-xl'
    #     })
    # }
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class':'w-full py-4 px-6 rounded-xl'
    }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class':'w-full py-4 px-6 rounded-xl'
    }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat Password',
        'class':'w-full py-4 px-6 rounded-xl'
    }
    ))

Bazaar/core/views.py
from django.shortcuts import render, redirect
# importing from the folder where you created item and category
from item.models import Category, Item
from .forms import SignupForm
# Create your views here.



def index(request):
    # core is the folder name inside template and this line has sepcified the path
    items=Item.objects.filter(is_sold=False)[0:6]
    categories=Category.objects.all()
    return render(request,'core/index.html',{
        'categories' : categories,
        'items' : items,
    })

def contact(request):
    # foldername (templatesname)/ webpage.html
    return render(request,'core/contact.html')

def loggedin(request):
    # core is the folder name inside template and this line has sepcified the path
    items=Item.objects.filter(is_sold=False)[0:6]
    categories=Category.objects.all()
    return render(request,'core/loggedin.html',{
        'categories' : categories,
        'items' : items,
    })

def signup(request):
    if request.method=='POST':
        # this makes it so that the class SignUpForm takes post request
        # form = SignupForm(attributes_of_a_class = '-')
        # form is an object
        
        form=SignupForm(request.POST)

        if form.is_valid():
            form.save()
            # the /login/ is the path in settings.py Login_url
            return redirect('/login/')
    else:
        # initial look of the page if theres no request
        form = SignupForm()

    return render(request,'core/signup.html',{
       # will be used in html
        'form': form
    })

Bazaar/core/templates/core/base.html
<!DOCTYPE html>
<!--This html is the page that is common throughout all route-->
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        <title>{%block title%}{%endblock%}| Bazaar</title>
    </head>
    <body>
        <!-- the class name is a tailwind css thing -->
        <!--this nav created a header type thing-->
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <!--clicking on the name of website redirects to home-->
            <a href="/" class=text-xl font-semibold>Bazaar</a>
            {% if request.user.is_authenticated %}
            <div class = "text-xl">
            {{request.user.username}}
            {%endif%}
            </div>

            <div class="space-x-6">
                <a href="{% url 'item:add' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
                <a href="{% url 'item:browse' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                <!-- url 'app_name:name="-" in urls.py for redirecting' -->
               
               {% if request.user.is_authenticated %}
            <!-- urls.py which upon clicking leads to LogOutView basically tells django to unauthenticate-->
               <a href="{% url 'core:logout' %}" class="text-lg font-semibold hover:text-gray-500">Logout</a>

               <a href="{% url 'message:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
               {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif%}
            </div>

        </nav>
        <div class="px-6 py-6">
          {% block content%}
          
          {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-500">PLEASE HELP ME IVE GONE INSANE</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul class="sapce-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                </div>
    </body>
</html>

Bazaar/core/templates/core/contact.html
{% extends 'core/base.html' %}


{% block title%}
    Contacts
{%endblock%}
{% block content%}
    <h1>Contact Page</h1>
{%endblock%}

Bazaar/core/templates/core/index.html
{% extends 'core/base.html' %}


{% block title%}
    Welcome
{%endblock%}
{% block content%}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center"> Newest Items</h2>

    <div class="grid grid-cols-3 gap-3">
        {%for item in items%}
        <div>
            <!--clicking on image redirects you to detail-->
            <!--app_name.name='-'-->
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{item.image.url}}" class="rounded-t-xl">
                </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{item.name}}</h2>
                <p class="text-black-100">Price:{{item.price}}</p>
            </div>
            </a>
        </div>
        {% endfor %}
         
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center"> Categories</h2>

    <div class="grid grid-cols-3 gap-3">
        <!-- categories is the key in the dict in views.py-->
        {% for category in categories%}
        
        <div>
            <a href="#">
               
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{category.name}}</h2>
                <p class="text-black-100">{{category.items.count}} items</p>
            </div>
            </a>
        </div>

        {%endfor%}
    </div>
</div>


{%endblock%}

Bazaar/core/templates/core/loggedin.html
{% extends 'core/base.html' %}


{% block title%}
    Welcome
{%endblock%}
{% block content%}
{% if request.user.is_authenticated%}
<p class="text-center text-lg">Welcome {{request.user.username}}</p>
{%endif%}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center"> Newest Items</h2>

    <div class="grid grid-cols-3 gap-3">
        {%for item in items%}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{item.image.url}}" class="rounded-t-xl">
                </div>
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{item.name}}</h2>
                <p class="text-black-100">Price:{{item.price}}</p>
            </div>
            </a>
        </div>
        {% endfor %}
         
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center"> Categories</h2>

    <div class="grid grid-cols-3 gap-3">
        <!-- categories is the key in the dict in views.py-->
        {% for category in categories%}
        
        <div>
            <a href="#">
               
            <div class="p-6 bg-white rounded-b-xl">
                <h2 class="text-2xl">{{category.name}}</h2>
                <!--.items is the related_name in Category class with category attributes-->
                <p class="text-black-100">{{category.items.count}} items</p>
            </div>
            </a>
        </div>

        {%endfor%}
    </div>
</div>


        {%endblock%}

Bazaar/core/templates/core/login.html
{%extends 'core/base.html'%}

{%block title%} Login {%endblock%}

{%block content%}
    <div class="w-1/2 my-6 mx-auto p-6 bg-red-100 rounded-xl">
        <h1 class = "mb-6 text-3xl">Login</h1>

        <form method="post" action=".">
            {% csrf_token %}
            <!--form is the key in views.py
            form.as_paragraph-->
            <!--{{ form.as_p}}-->
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                <!--value in dict.fields in forms.py-->
                <!--not for display but for taking in input-->
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                <!--value in dict.fields in forms.py-->
                {{form.password}}
            </div>
    
            {% if form.errors or form.non_field_errors%}
            <div class="bg-read-100 rounded-xl mb-3 p-6">
                {% for field in form%}
                {{ field.errors}}
                {% endfor%}

                {{ form.non_field_errors}}
                
            </div> 
            {% endif%}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"> Submit</button>

        </form>    
    </div>
{%endblock%}

Bazaar/core/templates/core/signup.html
{%extends 'core/base.html'%}

{%block title%} SignUp {%endblock%}

{%block content%}
    <div class="w-1/2 my-6 mx-auto p-6 bg-red-100 rounded-xl">
        <h1 class = "mb-6 text-3xl">Sign Up</h1>
            <!--action is used to indicate what to do when form is clicked
            in this case . means it should stay on the same page-->
        <form method="post" action=".">
            {% csrf_token %}
        
            <!--{{ form.as_p}}-->
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                <!--value in dict.fields in forms.py-->
                <!--not for display but for taking in input-->
                <!--form in inbuilt in  django when you call forms. somewhere-->
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{form.email}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                <!--value in dict.fields in forms.py-->
                {{form.password1}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Repeat Password</label><br>
                <!--value in dict.fields in forms.py-->
                {{form.password2}}
            </div>
            {% if form.errors or form.non_field_errors%}
            <div class="bg-read-100 rounded-xl mb-3 p-6">
                {% for field in form%}
                {{ field.errors}}
                {% endfor%}

                {{ form.non_field_errors}}
                
            </div> 
            {% endif%}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"> Submit</button>

        </form>    
    </div>
{%endblock%}